#!/bin/bash
 
while getopts ":q:" o; do
	case $o in
		q)
			q=${OPTARG}
			case $q in
				1)
					spark-submit CountLines.py $3 $4
					;;
				2)
					spark-submit SessionsOfUser.py $3 $4
					;;
				3)
					spark-submit UniqueUser.py $3 $4
					;;
				4)
					spark-submit SessionsPerUser.py $3 $4
					;;
				5)
					spark-submit NumberOfErrors.py $3 $4
					;;
				6)
					spark-submit FrequentErrors.py $3 $4
					;;
				7)
					spark-submit UsersOnBothHost.py $3 $4
					;;
				8)
					spark-submit UserOnlyOnOneHost.py $3 $4
					;;
				9)
					echo $q
					echo $3
					echo $4
					;;
				*)
					echo "question not found!!!"
					;;
			esac      
			;;
		\?)
			echo "Invalid option: -$OPTARG" >&2
			;;
	esac
done